### ISSUE TITLE
Replace all findViewById from onBindViewHolder to ViewHolder init block

### ISSUE THREAD

**Issue by Ulop** [akash-bisariya/Music-History#1]
https://github.com/akash-bisariya/Music-History/blob/4e4fc3ea42cb7fdf9cbd7516e95ae31b051c4846/app/src/main/java/app/android/com/musichistory/MusicRecyclerAdapter.kt#L39-L43

RecyclerView reuse already created ViewHolders.
You can use once calculated values instead call findViewById on each onBindViewHolder().
And make itemView non nullable.

```kotlin
 class ViewHolder(itemView: View, var onItemClick: IOnRecycleItemClick) : RecyclerView.ViewHolder(itemView){
    private val tvSongName = itemView.findViewById(R.id.tv_song_name) as TextView
    private val tvArtistName = itemView.findViewById(R.id.tv_artist_name) as TextView
    private val tvSongDuration = itemView.findViewById(R.id.tv_song_duration) as TextView
    private val tvSongPlayCount = itemView.findViewById(R.id.tv_song_play_count) as TextView

...
}
```

**Comment by akash-bisariya** [comment]
thanks @Ulop for pointing out this issue.
It would be great if you raise more such issues.
