### ISSUE TITLE
Dont't pass array

### ISSUE THREAD

**Issue by Ulop** [akash-bisariya/Music-History#2]
https://github.com/akash-bisariya/Music-History/blob/4e4fc3ea42cb7fdf9cbd7516e95ae31b051c4846/app/src/main/java/app/android/com/musichistory/MusicRecyclerAdapter.kt#L20

Don't pass array to ViewHolder. Pass SongHistory as param:
```kotlin
holder.viewHolderBind(isHistory, context, arrayList[position], onItemClick)
```
Each arrayList.get(adapterPosition) will increase bind time.

**Comment by akash-bisariya** [comment]
thanks @Ulop for giving your time to find this minor but critical issue.
I would be grateful if you raise more such issues.
