### ISSUE TITLE
If is expression

### ISSUE THREAD

**Issue by Ulop** [akash-bisariya/Music-History#3]
https://github.com/akash-bisariya/Music-History/blob/4e4fc3ea42cb7fdf9cbd7516e95ae31b051c4846/app/src/main/java/app/android/com/musichistory/MusicRecyclerAdapter.kt#L60-L63

In Kotlin 'if-else' block is expression.
You can write this code like this.
```kotlin
tvSongPlayCount.visibility = if (isHistory) View.VISIBLE else View.GONE
```

**Comment by akash-bisariya** [comment]
thanks @Ulop for pointing out issue.
More such issues will be appreciated.
