### ISSUE TITLE
when is expression

### ISSUE THREAD

**Issue by Ulop** [akash-bisariya/Music-History#4]
https://github.com/akash-bisariya/Music-History/blob/4e4fc3ea42cb7fdf9cbd7516e95ae31b051c4846/app/src/main/java/app/android/com/musichistory/PagerAdapter.kt#L11-L18

In Kotlin 'when' is expression. It can be written like this.
```kotlin
override fun getPageTitle(position: Int) = when (position) {
            0 -> "All Music"
            1 -> "Music History"
        }
```

**Comment by akash-bisariya** [comment]
thanks @Ulop for pointing this issue.
More such issues will be appreciated.
