### ISSUE TITLE
Single-line function

### ISSUE THREAD

**Issue by Ulop** [akash-bisariya/Music-History#5]
https://github.com/akash-bisariya/Music-History/blob/4b47aad4ed7058e7b1c82b4aa4b431d04c258f63/app/src/main/java/app/android/com/musichistory/PagerAdapter.kt#L17-L19

Kotlin support single-line functions. You can write it like this.
```kotlin
override fun getCount(): Int  = 2
//or more simple, without specifying the return type
override fun getCount() = 2
```

**Comment by akash-bisariya** [comment]
Resolved...
